# Generated by Django 6.0.4 on 2026-04-23 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('laboratorio', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_medida_minima', models.CharField(max_length=50)),
                ('stock_total', models.IntegerField(default=0)),
                ('stock_minimo_alerta', models.IntegerField(default=10)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='EmpaqueAlternativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empaque', models.CharField(max_length=100)),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('factor_conversion', models.IntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empaques', to='inventario.producto')),
            ],
        ),
    ]
