# Generated by Django 5.2.14 on 2026-05-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_venta_remove_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_presentacion',
            field=models.CharField(choices=[('SIMPLE', 'Unidad Simple (Cremas, Jarabes, Gotas)'), ('CAJA_UNIDAD', 'Caja a Unidades (Jeringas, Cuchillas)'), ('COMPLETO', 'Caja, Blíster y Unidad (Pastillas)')], default='COMPLETO', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidades_por_blister',
            field=models.IntegerField(default=1, help_text='Número de tabletas por blíster'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidades_por_caja',
            field=models.IntegerField(default=1, help_text='Número total de unidades por caja'),
        ),
    ]
